name: Build
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '25.3'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build benchClasses
      - run: ./gradlew run --args='examples/fib.za'
